// Generated by gencpp from file serial_cmd/serial.msg
// DO NOT EDIT!


#ifndef SERIAL_CMD_MESSAGE_SERIAL_H
#define SERIAL_CMD_MESSAGE_SERIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace serial_cmd
{
template <class ContainerAllocator>
struct serial_
{
  typedef serial_<ContainerAllocator> Type;

  serial_()
    : header()
    , cmd(0)  {
    }
  serial_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cmd(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::serial_cmd::serial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_cmd::serial_<ContainerAllocator> const> ConstPtr;

}; // struct serial_

typedef ::serial_cmd::serial_<std::allocator<void> > serial;

typedef boost::shared_ptr< ::serial_cmd::serial > serialPtr;
typedef boost::shared_ptr< ::serial_cmd::serial const> serialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_cmd::serial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_cmd::serial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_cmd

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'serial_cmd': ['/home/joeyyu/joeyyu-workplane/catkin_serial/src/serial_cmd/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_cmd::serial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_cmd::serial_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_cmd::serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_cmd::serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_cmd::serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_cmd::serial_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_cmd::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96d69b5d7ec20ad2ea96e00e9cdf8c75";
  }

  static const char* value(const ::serial_cmd::serial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96d69b5d7ec20ad2ULL;
  static const uint64_t static_value2 = 0xea96e00e9cdf8c75ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_cmd::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_cmd/serial";
  }

  static const char* value(const ::serial_cmd::serial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_cmd::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int8   cmd\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::serial_cmd::serial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_cmd::serial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_cmd::serial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_cmd::serial_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_CMD_MESSAGE_SERIAL_H
